# Docker compose file for the application on Digital Ocean.
# run
# sudo apt-get -y install python-pip
# sudo pip install docker-compose

#version: '2'   # on CircleCI the version and services cause build to puke.
#services:

  app:
    image: harbor.dev.o19s.com/pdf-discovery-demo/app:latest
    ports:
      - 8081:8080
    links:
      - solr

  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  solr:
    image: harbor.dev.o19s.com/pdf-discovery-demo/solr:latest
    ports:
     - "8983:8983"
    links:
      - zookeeper
    command: "bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181 -Dbootstrap_confdir=/solr-config/index/conf'"

  solr-proxy:
    image: harbor.dev.o19s.com/pdf-discovery-demo/solr-proxy:latest
    ports:
      - "8000:80"
    links:
      - solr

  init:
    image: harbor.dev.o19s.com/pdf-discovery-demo/init:latest
    ports:
     - "8080:8080"
    links:
      - solr
      - zookeeper

  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - "9998:9998"
