{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tika.serviceAccountName" . }}
  labels:
{{ include "tika.labels" . | nindent 4 }}
{{- end -}}
